# docker-w-conda.sub

universe = docker
docker_image = jsta/template_docker-w-conda:latest

log = docker-w-conda_$(Cluster).log
error = docker-w-conda_$(Cluster)_$(Process).err

executable = docker-w-conda.sh
arguments = $(Process)
output = docker-w-conda_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = hello.py,data.csv

request_cpus = 1
request_memory = 500MB
request_disk = 4GB

queue 1
