# py-data-sci.sub

universe = vanilla
log = job_$(Cluster).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

executable = py-data-sci.sh
arguments = $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/stachelek/py-data-sci.tar.gz, hello.py

request_cpus = 1
request_memory = 500MB
request_disk = 500MB

queue 1